// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char DEVICE_LOGIN_NAME[]  = "YOUR_DEVICE_LOGIN_NAME_HERE";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onPlantStatusChange();
void onAutoModeChange();
void onPumpSwitchChange();

String plant_status;
float humidity;
float temperature;
int soil_moisture;
bool auto_mode;
bool pump_switch;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(plant_status, READWRITE, ON_CHANGE, onPlantStatusChange);
  ArduinoCloud.addProperty(humidity, READ, ON_CHANGE, NULL, 5);
  ArduinoCloud.addProperty(temperature, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(soil_moisture, READ, ON_CHANGE, NULL, 5);
  ArduinoCloud.addProperty(auto_mode, READWRITE, ON_CHANGE, onAutoModeChange);
  ArduinoCloud.addProperty(pump_switch, READWRITE, ON_CHANGE, onPumpSwitchChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);